twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] // importer une forme du bootstrap.com
    debug: true

when@test:
    twig:
        strict_variables: true
